/**
 * The static documentation topics.
 */
HelpApp.TOPICS = [
    { topic: "RapidContext/1. Overview",
      url: "doc/platform.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/2. Client Programming",
      url: "doc/client.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/3. Server Programming",
      url: "doc/server.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/4. Users & Security",
      url: "doc/security.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/5. Command-line Plug-In",
      url: "doc/plugin-cmdline.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/6. HTTP Plug-In",
      url: "doc/plugin-http.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/7. JDBC Plug-In",
      url: "doc/plugin-jdbc.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.App",
      url: "doc/js/symbols/RapidContext.App.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Procedure",
      url: "doc/js/symbols/RapidContext.Procedure.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.SVG",
      url: "doc/js/symbols/RapidContext.SVG.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.UI",
      url: "doc/js/symbols/RapidContext.UI.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Util",
      url: "doc/js/symbols/RapidContext.Util.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget",
      url: "doc/js/symbols/RapidContext.Widget.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.Button",
      url: "doc/js/symbols/RapidContext.Widget.Button.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.Dialog",
      url: "doc/js/symbols/RapidContext.Widget.Dialog.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.Field",
      url: "doc/js/symbols/RapidContext.Widget.Field.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.Form",
      url: "doc/js/symbols/RapidContext.Widget.Form.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.FormValidator",
      url: "doc/js/symbols/RapidContext.Widget.FormValidator.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.Icon",
      url: "doc/js/symbols/RapidContext.Widget.Icon.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.NavigationBar",
      url: "doc/js/symbols/RapidContext.Widget.NavigationBar.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.Overlay",
      url: "doc/js/symbols/RapidContext.Widget.Overlay.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.Pane",
      url: "doc/js/symbols/RapidContext.Widget.Pane.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.Popup",
      url: "doc/js/symbols/RapidContext.Widget.Popup.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.ProgressBar",
      url: "doc/js/symbols/RapidContext.Widget.ProgressBar.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.TabContainer",
      url: "doc/js/symbols/RapidContext.Widget.TabContainer.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.Table",
      url: "doc/js/symbols/RapidContext.Widget.Table.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.TableColumn",
      url: "doc/js/symbols/RapidContext.Widget.TableColumn.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.TextArea",
      url: "doc/js/symbols/RapidContext.Widget.TextArea.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.TextField",
      url: "doc/js/symbols/RapidContext.Widget.TextField.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.Tree",
      url: "doc/js/symbols/RapidContext.Widget.Tree.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.TreeNode",
      url: "doc/js/symbols/RapidContext.Widget.TreeNode.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/RapidContext/RapidContext.Widget.Wizard",
      url: "doc/js/symbols/RapidContext.Widget.Wizard.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.Async",
      url: "doc/mochikit/Async.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.Base",
      url: "doc/mochikit/Base.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.Color",
      url: "doc/mochikit/Color.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.DateTime",
      url: "doc/mochikit/DateTime.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.DOM",
      url: "doc/mochikit/DOM.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.DragAndDrop",
      url: "doc/mochikit/DragAndDrop.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.Format",
      url: "doc/mochikit/Format.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.Iter",
      url: "doc/mochikit/Iter.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.Logging",
      url: "doc/mochikit/Logging.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.Selector",
      url: "doc/mochikit/Selector.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.Signal",
      url: "doc/mochikit/Signal.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.Sortable",
      url: "doc/mochikit/Sortable.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.Style",
      url: "doc/mochikit/Style.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.Text",
      url: "doc/mochikit/Text.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Client API/MochiKit/MochiKit.Visual",
      url: "doc/mochikit/Visual.html",
      source: "RapidContext Platform Documentation" },
    { topic: "RapidContext/Server API/Java API Overview",
      url: "doc/java/overview-summary.html",
      source: "RapidContext Platform Documentation" }
];
